import { neon, type NeonQueryFunction } from "@neondatabase/serverless";
import type { RazorpayWebhook, RecoveryStore, StoredCase } from "./types";

let sqlClient: NeonQueryFunction<false, false> | undefined;
let schemaReady: Promise<void> | undefined;
function sql() { if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is not configured"); sqlClient ??= neon(process.env.DATABASE_URL); return sqlClient; }

export function ensureRazorpaySchema() {
  schemaReady ??= (async () => {
    const db = sql();
    await db`CREATE TABLE IF NOT EXISTS webhook_events (event_id text PRIMARY KEY, event_type text NOT NULL, signature_valid boolean NOT NULL DEFAULT true, payload_hash text NOT NULL, payload jsonb NOT NULL, status text NOT NULL DEFAULT 'received', error text, received_at timestamptz NOT NULL DEFAULT now(), processed_at timestamptz)`;
    await db`CREATE TABLE IF NOT EXISTS recovery_cases (id text PRIMARY KEY, razorpay_payment_id text UNIQUE NOT NULL, razorpay_order_id text, amount_paise integer NOT NULL, currency text NOT NULL, failure_code text, failure_description text, state text NOT NULL, diagnosis jsonb NOT NULL, policy_decision jsonb NOT NULL, recovered_paise integer NOT NULL DEFAULT 0, recovered_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`;
    await db`CREATE TABLE IF NOT EXISTS recovery_actions (id text PRIMARY KEY, case_id text NOT NULL REFERENCES recovery_cases(id), idempotency_key text UNIQUE NOT NULL, reference_id text UNIQUE NOT NULL, action_type text NOT NULL, status text NOT NULL DEFAULT 'reserved', razorpay_payment_link_id text UNIQUE, short_url text, raw jsonb, error text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now())`;
    await db`CREATE TABLE IF NOT EXISTS audit_events (id bigserial PRIMARY KEY, case_id text, event_type text NOT NULL, actor text NOT NULL, details jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now())`;
    await db`CREATE INDEX IF NOT EXISTS audit_events_case_created_idx ON audit_events(case_id, created_at)`;
  })(); return schemaReady;
}

export class NeonRecoveryStore implements RecoveryStore {
  private async db() { await ensureRazorpaySchema(); return sql(); }
  async reserveWebhook(input: { eventId: string; eventType: string; payloadHash: string; payload: RazorpayWebhook }) { const db = await this.db(); const rows = await db`INSERT INTO webhook_events (event_id,event_type,payload_hash,payload) VALUES (${input.eventId},${input.eventType},${input.payloadHash},${JSON.stringify(input.payload)}::jsonb) ON CONFLICT (event_id) DO NOTHING RETURNING event_id`; return rows.length === 1; }
  async markWebhook(eventId: string, status: "processed" | "failed", error?: string) { const db = await this.db(); await db`UPDATE webhook_events SET status=${status},error=${error ?? null},processed_at=now() WHERE event_id=${eventId}`; }
  async upsertFailedCase(input: Parameters<RecoveryStore["upsertFailedCase"]>[0]): Promise<StoredCase> { const db = await this.db(); const orderId = typeof input.payment.order_id === "string" ? input.payment.order_id : null; const errorCode = typeof input.payment.error_code === "string" ? input.payment.error_code : null; const errorDescription = typeof input.payment.error_description === "string" ? input.payment.error_description : null; const state = input.result.allowed ? "approved" : "blocked"; const rows = await db`INSERT INTO recovery_cases (id,razorpay_payment_id,razorpay_order_id,amount_paise,currency,failure_code,failure_description,state,diagnosis,policy_decision) VALUES (${input.caseId},${input.record.id},${orderId},${input.record.amountPaise},${input.record.currency},${errorCode},${errorDescription},${state},${JSON.stringify(input.diagnosis)}::jsonb,${JSON.stringify({ allowed: input.result.allowed, action: input.result.action, rule: input.result.rule, reason: input.result.reason })}::jsonb) ON CONFLICT (razorpay_payment_id) DO UPDATE SET diagnosis=EXCLUDED.diagnosis,policy_decision=EXCLUDED.policy_decision,updated_at=now() RETURNING id,razorpay_payment_id,amount_paise,currency,state`; const row = rows[0] as Record<string, unknown>; return { id: String(row.id), razorpayPaymentId: String(row.razorpay_payment_id), amountPaise: Number(row.amount_paise), currency: String(row.currency), state: String(row.state) }; }
  async reserveAction(input: Parameters<RecoveryStore["reserveAction"]>[0]) { const db = await this.db(); const rows = await db`INSERT INTO recovery_actions (id,case_id,idempotency_key,reference_id,action_type) VALUES (${input.actionId},${input.caseId},${input.idempotencyKey},${input.referenceId},${input.actionType}) ON CONFLICT DO NOTHING RETURNING id`; return rows.length === 1; }
  async completeAction(input: Parameters<RecoveryStore["completeAction"]>[0]) { const db = await this.db(); await db`UPDATE recovery_actions SET status='link_issued',razorpay_payment_link_id=${input.paymentLinkId},short_url=${input.shortUrl},raw=${JSON.stringify(input.raw)}::jsonb,updated_at=now() WHERE id=${input.actionId}`; await db`UPDATE recovery_cases SET state='link_issued',updated_at=now() WHERE id=(SELECT case_id FROM recovery_actions WHERE id=${input.actionId})`; }
  async failAction(actionId: string, reason: string) { const db = await this.db(); await db`UPDATE recovery_actions SET status='failed',error=${reason},updated_at=now() WHERE id=${actionId}`; }
  async markRecoveredByReference(input: Parameters<RecoveryStore["markRecoveredByReference"]>[0]) { const db = await this.db(); const rows = await db`UPDATE recovery_actions SET status='paid',raw=${JSON.stringify(input.raw)}::jsonb,updated_at=now() WHERE reference_id=${input.referenceId} OR razorpay_payment_link_id=${input.paymentLinkId ?? null} RETURNING case_id`; if (!rows.length) return false; await db`UPDATE recovery_cases SET state='recovered',recovered_paise=${input.recoveredPaise},recovered_at=now(),updated_at=now() WHERE id=${String((rows[0] as Record<string, unknown>).case_id)}`; return true; }
  async appendAudit(caseId: string | null, eventType: string, actor: string, details: unknown) { const db = await this.db(); await db`INSERT INTO audit_events (case_id,event_type,actor,details) VALUES (${caseId},${eventType},${actor},${JSON.stringify(details)}::jsonb)`; }
}
export const recoveryStore = new NeonRecoveryStore();
