"use client";
import { useState } from "react";
import { Activity, Ban, CheckCircle2, CopyCheck, IndianRupee, KeyRound, Link2, RefreshCw } from "lucide-react";
import type { OperationsSnapshot } from "@/lib/razorpay/operations";
import styles from "./operations.module.css";

const money=(paise:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(paise/100);
const time=(value:string)=>new Date(value).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"});

export function OperationsClient(){const[token,setToken]=useState("");const[data,setData]=useState<OperationsSnapshot|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  async function load(){setBusy(true);setError("");try{const response=await fetch("/api/razorpay/operations",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"});if(!response.ok)throw new Error(response.status===401?"Dashboard passcode is missing or incorrect.":"Live evidence is temporarily unavailable.");setData(await response.json() as OperationsSnapshot);}catch(reason){setError(reason instanceof Error?reason.message:"Unable to load evidence.");}finally{setBusy(false);}}
  if(!data)return <section className={styles.lock}><KeyRound size={30}/><div><small>JUDGE MODE</small><h2>Unlock persisted evidence</h2><p>The passcode protects real webhook metadata. It is kept in memory only and never saved by the browser.</p></div><div className={styles.unlock}><input aria-label="Operations dashboard passcode" type="password" value={token} onChange={event=>setToken(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")void load();}} placeholder="Dashboard passcode"/><button onClick={()=>void load()} disabled={busy||!token}>{busy?<RefreshCw className={styles.spin} size={16}/>:<KeyRound size={16}/>} Unlock</button></div>{error&&<p className={styles.error} role="alert">{error}</p>}</section>;
  const cards=[{label:"Cases received",value:data.metrics.cases,icon:Activity},{label:"Links issued",value:data.metrics.linksIssued,icon:Link2},{label:"Recovered",value:data.metrics.recovered,icon:CheckCircle2},{label:"Blocked safely",value:data.metrics.blocked,icon:Ban},{label:"Duplicate deliveries",value:data.metrics.duplicates,icon:CopyCheck},{label:"Confirmed recovered",value:money(data.metrics.recoveredPaise),icon:IndianRupee}];
  return <section className={styles.workspace}><div className={styles.toolbar}><div><i/>Razorpay test mode · Neon persisted</div><span>Snapshot {time(data.generatedAt)}</span><button onClick={()=>void load()} disabled={busy}><RefreshCw className={busy?styles.spin:""} size={15}/> Refresh</button></div><div className={styles.metrics}>{cards.map(({label,value,icon:Icon})=><article key={label}><Icon size={18}/><small>{label}</small><strong>{value}</strong></article>)}</div><div className={styles.grid}><article className={styles.panel}><header><div><small>RECOVERY CASES</small><h2>Latest decisions</h2></div><span>{data.cases.length} shown</span></header>{data.cases.length?data.cases.map((item,index)=><div className={styles.row} key={`${item.updatedAt}-${index}`}><span className={`${styles.state} ${styles[item.state]??""}`}>{item.state.replaceAll("_"," ")}</span><div><strong>{item.diagnosis.replaceAll("_"," ")}</strong><small>{item.policy.replaceAll("_"," ")} · {item.action??"no action"}</small></div><time>{time(item.updatedAt)}</time></div>):<Empty text="Send a signed payment.failed test webhook to create the first case."/>}</article><article className={styles.panel}><header><div><small>WEBHOOK LEDGER</small><h2>Delivery proof</h2></div><span>Idempotent</span></header>{data.events.length?data.events.map((item,index)=><div className={styles.row} key={`${item.receivedAt}-${index}`}><span className={`${styles.state} ${styles[item.status]??""}`}>{item.status}</span><div><strong>{item.type}</strong><small>{item.deliveries} deliver{item.deliveries===1?"y":"ies"}</small></div><time>{time(item.receivedAt)}</time></div>):<Empty text="No webhook deliveries recorded yet."/>}</article></div><article className={styles.audit}><header><div><small>AUDIT TIMELINE</small><h2>What the system actually did</h2></div><span>No customer fields exposed</span></header><div>{data.audit.length?data.audit.map((item,index)=><p key={`${item.createdAt}-${index}`}><i/><time>{time(item.createdAt)}</time><strong>{item.type.replaceAll("_"," ")}</strong><span>{item.actor}</span></p>):<Empty text="Audit events will appear after the first accepted webhook."/>}</div></article></section>;
}
function Empty({text}:{text:string}){return <div className={styles.empty}>{text}</div>}
